### PR TITLE
Added Czech localization for reports

### PR DESCRIPTION
**Pull request by p-bo**

### CODE REVIEW

**Comment by trasher** [comment]
Could you please rebase on the develop branch?

**Comment by p-bo** [comment]
Yes, of course :)

**Comment by trasher** [comment]
> It seems that on Transifex there aren't strings for reports - thus contributing this way.
Indeed; this is currently the way to go ;)

**Comment by p-bo** [comment]
Don't know how to rebase, so doing in less elegant way - closing and doing new pull request - sorry for that...

**Pull request closed without merging**
