### PR TITLE
Portuguese (pt_PT) translation

### PR DESCRIPTION
**Pull request by eSkiSo**

### CODE REVIEW

**Comment by trasher** [comment]
Hello,

Thank you for your pull request, but this is not OK... I do not know where you find this way of translation; the plugin is using gettext for a while (and not php files).

If you want to add a new translation, you have to go to the transifex project (https://www.transifex.com/teclib/glpi-project-plugin-mreporting/dashboard/), and ask other there.

**Comment by eSkiSo** [comment]
Hello, i've asked for pt_PT in transifex, waiting for approval so i can request join, as for the PHP files if you go to : **locales/reports_locales**, several translations are there, the last one was updated 5 months ago

**Comment by trasher** [comment]
You are right; I was not aware about this directory... It should be used to translate user reports; but not main plugin ones.

We'll check if this is still used. It should not as far as I know; but maybe it has not been migrated. I reopen the PR for now; waiting to be sure.

Thank you!

**Comment by trasher** [comment]
Could you please rebase on the develop branch?

**Comment by trasher** [comment]
Nevermind, I've merged in develop. Thank you.

**Pull request closed without merging**
